In [28]:
import pandas as pd

In [29]:
teams = pd.read_csv("../teams/top_50_teams.csv")
matches = pd.read_csv("../matches/top_50_team_matches.csv")
failed_player_stats = pd.read_csv("../matches/failed_match_player_stats.csv")
player_stats = pd.read_csv("../matches/top_50_team_match_player_stats.csv")

In [30]:
print(len(matches))
failed_indexes = matches[matches["match_id"].isin(failed_player_stats["match_id"])].index

matches = matches.drop(failed_indexes)
print(len(matches))

1929
1912

In [31]:

print(teams.describe())

print(matches.describe())

print(player_stats.describe())

                 id  hltv_placement  hltv_points  valve_placement  \
count     50.000000        50.00000    50.000000        50.000000
mean    9810.560000        25.50000   155.040000        28.460000
std     3124.281411        14.57738   194.024821        21.340973
min     4411.000000         1.00000    21.000000         1.000000
25%     6759.750000        13.25000    38.500000        13.250000
50%    10700.000000        25.50000    73.000000        25.500000
75%    12467.750000        37.75000   205.000000        37.750000
max    13808.000000        50.00000  1000.000000       108.000000

       valve_points
count     50.000000
mean    1501.860000
std      234.610577
min      988.000000
25%     1338.500000
50%     1433.000000
75%     1672.750000
max     2012.000000
           match_id     team_1_id   team_score     team_2_id  team2_score
count  1.912000e+03   1912.000000  1912.000000   1912.000000  1912.000000
mean   2.384142e+06   8957.513075     2.414749   9068.342050     2.302301
std    7.929083e+03   2990.181330     3.319235   3076.385219     3.501758
min    2.335359e+06   4411.000000     0.000000   4411.000000     0.000000
25%    2.379358e+06   6248.000000     1.000000   6248.000000     0.000000
50%    2.385320e+06   9215.000000     2.000000   9215.000000     2.000000
75%    2.389977e+06  11861.000000     2.000000  12376.000000     2.000000
max    2.394866e+06  13808.000000    17.000000  13808.000000    19.000000
           match_id     team_1_id     team_2_id  player_team_id     player_id  \
count  1.912000e+04  19120.000000  19120.000000    19120.000000  19120.000000
mean   2.384142e+06   8957.513075   9068.342050     9012.927563  17180.622803
std    7.927217e+03   2989.477455   3075.661051     3033.381628   5652.002819
min    2.335359e+06   4411.000000   4411.000000     4411.000000     29.000000
25%    2.379358e+06   6248.000000   6248.000000     6248.000000  13497.000000
50%    2.385320e+06   9215.000000   9215.000000     9215.000000  19230.000000
75%    2.389977e+06  11861.000000  12376.000000    12257.000000  21217.000000
max    2.394866e+06  13808.000000  13808.000000    13808.000000  25807.000000

         rating_3_0  rating_3_0_t_rating  rating_3_0_ct_rating   round_swing  \
count  18508.000000         18508.000000          18508.000000  18508.000000
mean       1.059861             1.053384              1.066859      0.333380
std        0.093661             0.111576              0.101769      1.069623
min        0.430000             0.360000              0.500000     -9.160000
25%        1.000000             0.980000              1.000000     -0.340000
50%        1.060000             1.050000              1.070000      0.350000
75%        1.120000             1.130000              1.130000      1.030000
max        1.500000             1.620000              1.670000      4.690000

                dpr  ...    multi_kill           adr           kpr  \
count  19081.000000  ...  18508.000000  19081.000000  19081.000000
mean       0.651617  ...     16.321094     73.932404      0.676979
std        0.042798  ...      2.405633      6.217068      0.067318
min        0.460000  ...      0.000000     35.400000      0.280000
25%        0.630000  ...     14.800000     69.500000      0.630000
50%        0.660000  ...     16.400000     73.900000      0.680000
75%        0.680000  ...     17.900000     78.100000      0.720000
max        1.000000  ...     29.300000    100.400000      0.990000

       firepower_combined_score  entrying_combined_score  \
count              19081.000000              19081.00000
mean                  55.706043                 52.84592
std                   24.013534                 23.86388
min                    0.000000                  0.00000
25%                   37.000000                 34.00000
50%                   57.000000                 54.00000
75%                   75.000000                 72.00000
max                  100.000000                100.00000

       trading_combined_score  opening_combined_score  \
count            19081.000000            19081.000000
mean                49.179079               51.876579
std                 19.668683               21.254424
min                  0.000000                0.000000
25%                 34.000000               34.000000
50%                 50.000000               52.000000
75%                 65.000000               69.000000
max                 99.000000               98.000000

       clutching_combined_score  sniping_combined_score  \
count              19081.000000            19081.000000
mean                  52.235889               18.326398
std                   17.704787               35.661443
min                    0.000000                0.000000
25%                   39.000000                0.000000
50%                   51.000000                0.000000
75%                   65.000000                3.000000
max                   98.000000               96.000000

       utility_combined_score
count            19081.000000
mean                57.643363
std                 18.264075
min                  7.000000
25%                 45.000000
50%                 58.000000
75%                 71.000000
max                 97.000000

[8 rows x 21 columns]

In [32]:
empty_stats_teams = teams[teams.isna().any(axis=1)]
empty_stats_teams

Empty DataFrame
Columns: [team_name, id, hltv_placement, hltv_points, valve_placement, valve_points]
Index: []

In [33]:
empty_stats_match = matches[matches.isna().any(axis=1)]
empty_stats_match

Empty DataFrame
Columns: [match_id, team_1_id, team_1, team_score, team_2_id, team_2, team2_score, team_1_winner, match_date, event_name]
Index: []

In [34]:
empty_stats = player_stats[player_stats.isna().any(axis=1)]
empty_stats

,match_id,match_date,event_name,team_1_id,team_1,team_2_id,team_2,player_team_id,player_team_name,player_id,...,multi_kill,adr,kpr,firepower_combined_score,entrying_combined_score,trading_combined_score,opening_combined_score,clutching_combined_score,sniping_combined_score,utility_combined_score
12075,2388920,2026-01-22,IEM Rio 2026 Closed Qualifier,13404,Gentle Mates,13355,Nemesis,13404,Gentle Mates,22536,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12076,2388920,2026-01-22,IEM Rio 2026 Closed Qualifier,13404,Gentle Mates,13355,Nemesis,13404,Gentle Mates,23047,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12077,2388920,2026-01-22,IEM Rio 2026 Closed Qualifier,13404,Gentle Mates,13355,Nemesis,13404,Gentle Mates,24485,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12078,2388920,2026-01-22,IEM Rio 2026 Closed Qualifier,13404,Gentle Mates,13355,Nemesis,13404,Gentle Mates,22930,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13215,2392862,2026-04-05,Yuqilin Pinnacle of Battle Season 3,4863,TYLOO,8840,Lynn Vision,4863,TYLOO,8601,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19115,2362232,2023-03-21,ESL Pro League Season 17,4991,fnatic,8297,FURIA,4991,fnatic,13602,...,NaN,70.3,0.67,46.0,9.0,26.0,49.0,75.0,89.0,70.0
19116,2362232,2023-03-21,ESL Pro League Season 17,4991,fnatic,8297,FURIA,4991,fnatic,14419,...,NaN,75.8,0.65,52.0,66.0,26.0,77.0,22.0,0.0,60.0
19117,2362232,2023-03-21,ESL Pro League Season 17,4991,fnatic,8297,FURIA,4991,fnatic,11954,...,NaN,71.2,0.63,37.0,83.0,44.0,41.0,51.0,0.0,47.0
19118,2362232,2023-03-21,ESL Pro League Season 17,4991,fnatic,8297,FURIA,4991,fnatic,7528,...,NaN,71.4,0.65,46.0,30.0,37.0,29.0,79.0,0.0,67.0
19119,2362232,2023-03-21,ESL Pro League Season 17,4991,fnatic,8297,FURIA,4991,fnatic,18462,...,NaN,74.0,0.66,50.0,54.0,50.0,29.0,61.0,0.0,78.0

In [35]:
print(f"len matches {len(matches)}")
set_missed_matches = set(empty_stats["match_id"])

matches.drop(matches[matches.match_id.isin(set_missed_matches)].index, axis = 0, inplace = True)
print(f"len matches after filter {len(matches)}")

len matches 1912
len matches after filter 1831

In [36]:
team_features = [
    "id",
    "hltv_placement",
    "hltv_points",
    "valve_placement",
    "valve_points",
]

team_1_org = teams[team_features].rename(columns={
    "id": "team_1_id",
    "hltv_placement": "team_1_hltv_placement",
    "hltv_points": "team_1_hltv_points",
    "valve_placement": "team_1_valve_placement",
    "valve_points": "team_1_valve_points",
})

team_2_org = teams[team_features].rename(columns={
    "id": "team_2_id",
    "hltv_placement": "team_2_hltv_placement",
    "hltv_points": "team_2_hltv_points",
    "valve_placement": "team_2_valve_placement",
    "valve_points": "team_2_valve_points",
})

match_df = matches.merge(team_1_org, on="team_1_id", how="left")
match_df = match_df.merge(team_2_org, on="team_2_id", how="left")

match_df

,match_id,team_1_id,team_1,team_score,team_2_id,team_2,team2_score,team_1_winner,match_date,event_name,team_1_hltv_placement,team_1_hltv_points,team_1_valve_placement,team_1_valve_points,team_2_hltv_placement,team_2_hltv_points,team_2_valve_placement,team_2_valve_points
0,2394174,9565,Vitality,1,4608,Natus Vincere,2,False,2026-05-16,IEM Atlanta 2026,1,1000,1,2012,2,711,4,1943
1,2394170,9565,Vitality,2,11241,B8,0,True,2026-05-13,IEM Atlanta 2026,1,1000,1,2012,16,154,16,1613
2,2394166,9565,Vitality,2,6667,FaZe,0,True,2026-05-13,IEM Atlanta 2026,1,1000,1,2012,15,171,22,1487
3,2394157,9565,Vitality,1,12394,BetBoom,2,False,2026-05-12,IEM Atlanta 2026,1,1000,1,2012,21,110,17,1607
4,2394108,9565,Vitality,2,12878,BC.Game,0,True,2026-05-11,IEM Atlanta 2026,1,1000,1,2012,44,25,108,988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1826,2370143,4991,fnatic,2,4914,3DMAX,1,True,2024-03-04,RES Regional Series 1 Europe,49,21,81,1110,22,101,27,1427
1827,2370084,4991,fnatic,0,9928,GamerLegion,2,False,2024-02-23,PGL CS2 Major Copenhagen 2024 Europe Last Chan...,49,21,81,1110,10,265,10,1711
1828,2369726,4991,fnatic,13,12394,BetBoom,6,True,2024-02-14,PGL CS2 Major Copenhagen 2024 Europe RMR A,49,21,81,1110,21,110,17,1607
1829,2369711,4991,fnatic,9,4914,3DMAX,13,False,2024-02-09,RES Western European Masters Spring 2024 - BLA...,49,21,81,1110,22,101,27,1427
1830,2369240,4991,fnatic,13,10577,SINNERS,7,True,2024-01-18,PGL CS2 Major Copenhagen 2024 Europe RMR Close...,49,21,81,1110,30,52,42,1319

In [37]:
player_stats["team_side"] = player_stats.apply(
    lambda row: "team_1" if row["player_team_id"] == row["team_1_id"] else "team_2",
    axis=1
)

player_stats

,match_id,match_date,event_name,team_1_id,team_1,team_2_id,team_2,player_team_id,player_team_name,player_id,...,adr,kpr,firepower_combined_score,entrying_combined_score,trading_combined_score,opening_combined_score,clutching_combined_score,sniping_combined_score,utility_combined_score,team_side
0,2394174,2026-05-16,IEM Atlanta 2026,9565,Vitality,4608,Natus Vincere,4608,Natus Vincere,20127,...,72.0,0.75,71.0,24.0,85.0,61.0,82.0,92.0,57.0,team_2
1,2394174,2026-05-16,IEM Atlanta 2026,9565,Vitality,4608,Natus Vincere,4608,Natus Vincere,18987,...,75.8,0.70,66.0,47.0,81.0,37.0,64.0,1.0,54.0,team_2
2,2394174,2026-05-16,IEM Atlanta 2026,9565,Vitality,4608,Natus Vincere,4608,Natus Vincere,14759,...,76.9,0.69,71.0,80.0,55.0,69.0,31.0,0.0,38.0,team_2
3,2394174,2026-05-16,IEM Atlanta 2026,9565,Vitality,4608,Natus Vincere,4608,Natus Vincere,22673,...,83.8,0.76,88.0,91.0,39.0,87.0,37.0,0.0,51.0,team_2
4,2394174,2026-05-16,IEM Atlanta 2026,9565,Vitality,4608,Natus Vincere,4608,Natus Vincere,9816,...,60.3,0.51,4.0,88.0,42.0,11.0,48.0,0.0,91.0,team_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19115,2362232,2023-03-21,ESL Pro League Season 17,4991,fnatic,8297,FURIA,4991,fnatic,13602,...,70.3,0.67,46.0,9.0,26.0,49.0,75.0,89.0,70.0,team_1
19116,2362232,2023-03-21,ESL Pro League Season 17,4991,fnatic,8297,FURIA,4991,fnatic,14419,...,75.8,0.65,52.0,66.0,26.0,77.0,22.0,0.0,60.0,team_1
19117,2362232,2023-03-21,ESL Pro League Season 17,4991,fnatic,8297,FURIA,4991,fnatic,11954,...,71.2,0.63,37.0,83.0,44.0,41.0,51.0,0.0,47.0,team_1
19118,2362232,2023-03-21,ESL Pro League Season 17,4991,fnatic,8297,FURIA,4991,fnatic,7528,...,71.4,0.65,46.0,30.0,37.0,29.0,79.0,0.0,67.0,team_1
19119,2362232,2023-03-21,ESL Pro League Season 17,4991,fnatic,8297,FURIA,4991,fnatic,18462,...,74.0,0.66,50.0,54.0,50.0,29.0,61.0,0.0,78.0,team_1

In [38]:
player_stats["player_slot"] = (
    player_stats
    .groupby(["match_id", "team_side"])
    .cumcount() + 1
)

player_feature_cols = [
    "player_name",
    "player_id",
    "rating_3_0",
    "rating_3_0_t_rating",
    "rating_3_0_ct_rating",
    "round_swing",
    "dpr",
    "kast",
    "multi_kill",
    "adr",
    "kpr",
    "firepower_combined_score",
    "entrying_combined_score",
    "trading_combined_score",
    "opening_combined_score",
    "clutching_combined_score",
    "sniping_combined_score",
    "utility_combined_score",
]

player_wide = player_stats[
    ["match_id", "team_side", "player_slot"] + player_feature_cols
].pivot(
    index="match_id",
    columns=["team_side", "player_slot"],
    values=player_feature_cols
)

player_wide.columns = [
    f"{team_side}_player_{player_slot}_{feature}"
    for feature, team_side, player_slot in player_wide.columns
]

player_wide = player_wide.reset_index()

final_df = match_df.merge(player_wide, on="match_id", how="left")

final_df["target_team_1_win"] = final_df["team_1_winner"].astype(int)

In [39]:
final_df["winner_team_id"] = final_df.apply(
    lambda row: row["team_1_id"] if row["team_1_winner"] else row["team_2_id"],
    axis=1
)

final_df["winner_team_name"] = final_df.apply(
    lambda row: row["team_1"] if row["team_1_winner"] else row["team_2"],
    axis=1
)

final_df

,match_id,team_1_id,team_1,team_score,team_2_id,team_2,team2_score,team_1_winner,match_date,event_name,...,team_2_player_4_utility_combined_score,team_2_player_5_utility_combined_score,team_1_player_1_utility_combined_score,team_1_player_2_utility_combined_score,team_1_player_3_utility_combined_score,team_1_player_4_utility_combined_score,team_1_player_5_utility_combined_score,target_team_1_win,winner_team_id,winner_team_name
0,2394174,9565,Vitality,1,4608,Natus Vincere,2,False,2026-05-16,IEM Atlanta 2026,...,51.0,91.0,27.0,67.0,61.0,66.0,96.0,0,4608,Natus Vincere
1,2394170,9565,Vitality,2,11241,B8,0,True,2026-05-13,IEM Atlanta 2026,...,36.0,20.0,61.0,67.0,27.0,96.0,66.0,1,9565,Vitality
2,2394166,9565,Vitality,2,6667,FaZe,0,True,2026-05-13,IEM Atlanta 2026,...,24.0,65.0,67.0,27.0,96.0,66.0,61.0,1,9565,Vitality
3,2394157,9565,Vitality,1,12394,BetBoom,2,False,2026-05-12,IEM Atlanta 2026,...,33.0,74.0,67.0,66.0,27.0,61.0,96.0,0,12394,BetBoom
4,2394108,9565,Vitality,2,12878,BC.Game,0,True,2026-05-11,IEM Atlanta 2026,...,96.0,61.0,60.0,57.0,33.0,56.0,45.0,1,9565,Vitality
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1826,2370143,4991,fnatic,2,4914,3DMAX,1,True,2024-03-04,RES Regional Series 1 Europe,...,64.0,44.0,73.0,41.0,52.0,67.0,82.0,1,4991,fnatic
1827,2370084,4991,fnatic,0,9928,GamerLegion,2,False,2024-02-23,PGL CS2 Major Copenhagen 2024 Europe Last Chan...,...,82.0,67.0,63.0,74.0,27.0,50.0,28.0,0,9928,GamerLegion
1828,2369726,4991,fnatic,13,12394,BetBoom,6,True,2024-02-14,PGL CS2 Major Copenhagen 2024 Europe RMR A,...,48.0,29.0,82.0,41.0,73.0,67.0,52.0,1,4991,fnatic
1829,2369711,4991,fnatic,9,4914,3DMAX,13,False,2024-02-09,RES Western European Masters Spring 2024 - BLA...,...,73.0,67.0,39.0,84.0,62.0,64.0,44.0,0,4914,3DMAX
1830,2369240,4991,fnatic,13,10577,SINNERS,7,True,2024-01-18,PGL CS2 Major Copenhagen 2024 Europe RMR Close...,...,55.0,61.0,73.0,67.0,52.0,41.0,82.0,1,4991,fnatic

In [40]:
empty_stats = final_df[final_df.isna().any(axis=1)]
empty_stats

Empty DataFrame
Columns: [match_id, team_1_id, team_1, team_score, team_2_id, team_2, team2_score, team_1_winner, match_date, event_name, team_1_hltv_placement, team_1_hltv_points, team_1_valve_placement, team_1_valve_points, team_2_hltv_placement, team_2_hltv_points, team_2_valve_placement, team_2_valve_points, team_2_player_1_player_name, team_2_player_2_player_name, team_2_player_3_player_name, team_2_player_4_player_name, team_2_player_5_player_name, team_1_player_1_player_name, team_1_player_2_player_name, team_1_player_3_player_name, team_1_player_4_player_name, team_1_player_5_player_name, team_2_player_1_player_id, team_2_player_2_player_id, team_2_player_3_player_id, team_2_player_4_player_id, team_2_player_5_player_id, team_1_player_1_player_id, team_1_player_2_player_id, team_1_player_3_player_id, team_1_player_4_player_id, team_1_player_5_player_id, team_2_player_1_rating_3_0, team_2_player_2_rating_3_0, team_2_player_3_rating_3_0, team_2_player_4_rating_3_0, team_2_player_5_rating_3_0, team_1_player_1_rating_3_0, team_1_player_2_rating_3_0, team_1_player_3_rating_3_0, team_1_player_4_rating_3_0, team_1_player_5_rating_3_0, team_2_player_1_rating_3_0_t_rating, team_2_player_2_rating_3_0_t_rating, team_2_player_3_rating_3_0_t_rating, team_2_player_4_rating_3_0_t_rating, team_2_player_5_rating_3_0_t_rating, team_1_player_1_rating_3_0_t_rating, team_1_player_2_rating_3_0_t_rating, team_1_player_3_rating_3_0_t_rating, team_1_player_4_rating_3_0_t_rating, team_1_player_5_rating_3_0_t_rating, team_2_player_1_rating_3_0_ct_rating, team_2_player_2_rating_3_0_ct_rating, team_2_player_3_rating_3_0_ct_rating, team_2_player_4_rating_3_0_ct_rating, team_2_player_5_rating_3_0_ct_rating, team_1_player_1_rating_3_0_ct_rating, team_1_player_2_rating_3_0_ct_rating, team_1_player_3_rating_3_0_ct_rating, team_1_player_4_rating_3_0_ct_rating, team_1_player_5_rating_3_0_ct_rating, team_2_player_1_round_swing, team_2_player_2_round_swing, team_2_player_3_round_swing, team_2_player_4_round_swing, team_2_player_5_round_swing, team_1_player_1_round_swing, team_1_player_2_round_swing, team_1_player_3_round_swing, team_1_player_4_round_swing, team_1_player_5_round_swing, team_2_player_1_dpr, team_2_player_2_dpr, team_2_player_3_dpr, team_2_player_4_dpr, team_2_player_5_dpr, team_1_player_1_dpr, team_1_player_2_dpr, team_1_player_3_dpr, team_1_player_4_dpr, team_1_player_5_dpr, team_2_player_1_kast, team_2_player_2_kast, team_2_player_3_kast, team_2_player_4_kast, team_2_player_5_kast, team_1_player_1_kast, team_1_player_2_kast, team_1_player_3_kast, team_1_player_4_kast, team_1_player_5_kast, team_2_player_1_multi_kill, team_2_player_2_multi_kill, ...]
Index: []

[0 rows x 201 columns]

In [41]:
final_df.to_csv('training_dataset.csv', index=False)